version: '3.8'

services:
  postgres:
    image: postgres
    container_name: example-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - webserver

networks:
  webserver:
    driver: bridge